{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleDemo",
    "module": "myplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "MyPlugin-1.0.0.jar",
          "url": "MyPlugin-1.0.0.jar",
          "size": 11412,
          "sha512": "eb4e1e2e7216f9ea7611938c2de9542bb6b4baa816d7d9511fabfc5a2daa02417601e7b2ea6c3fcabe59c5766e92949da8fe8049400b222d64804f0320211c09",
          "sha256": "b93cf0f20fc1be9fd04618c0ce959a6925e9566be8dc55b59bfdd5c8e1504f39",
          "sha1": "a89a0969e97fe6d05762ae01fac1b9125b83cce0",
          "md5": "ea7f931ef353cbc60416eb1045393a2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "MyPlugin-1.0.0.jar",
          "url": "MyPlugin-1.0.0.jar",
          "size": 11412,
          "sha512": "eb4e1e2e7216f9ea7611938c2de9542bb6b4baa816d7d9511fabfc5a2daa02417601e7b2ea6c3fcabe59c5766e92949da8fe8049400b222d64804f0320211c09",
          "sha256": "b93cf0f20fc1be9fd04618c0ce959a6925e9566be8dc55b59bfdd5c8e1504f39",
          "sha1": "a89a0969e97fe6d05762ae01fac1b9125b83cce0",
          "md5": "ea7f931ef353cbc60416eb1045393a2c"
        }
      ]
    }
  ]
}
